FROM node:16-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++ 

# Copy package.json and package-lock.json (if they exist)
COPY graphql-server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY graphql-server .

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["node", "index.js"]
